### ISSUE TITLE
API CALLED FAILED DURING NSFW SCAN

### ISSUE THREAD

**Issue by ArshCypherZ** [AsmSafone/SafoneAPI#9]
pyrogram.dispatcher - ERROR - Api Call Failed, Please report this: https://api.safone.me/report
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/Emilia/modules/antinsfw.py", line 90, in detect_nsfw
    results = await api.nsfw_scan(file=nya)
  File "/usr/local/lib/python3.10/site-packages/SafoneAPI/__init__.py", line 758, in nsfw_scan
    return await self._post_data("nsfw", data={"image": file})
  File "/usr/local/lib/python3.10/site-packages/SafoneAPI/__init__.py", line 95, in _post_data
    raise GenericApiError(
SafoneAPI.GenericApiError: Api Call Failed, Please report this: https://api.safone.me/report

**Comment by AsmSafone** [comment]
Can you share reproducible example? 
Look like u used to send invalid buffer (image)
